/*更新路由方向*/
const UPDATE_DIRECTION = 'UPDATE_DIRECTION';
/*存储 openId */
const SET_USERINFO = 'SET_USERINFO';
/*获取 openId */
const GET_USERINFO = 'GET_USERINFO';

/*存储 订单列表 */
const SAVE_ORDERLIST = 'SAVE_ORDERLIST';
/*获取 获取订单列表 */
const GET_ORDERLIST = 'GET_ORDERLIST';

/*存储 入库单列表 */
const SAVE_WAREHOUSINGLIST = 'SAVE_WAREHOUSINGLIST';
/*获取 获取入库单列表 */
const GET_WAREHOUSINGLIST = 'GET_WAREHOUSINGLIST';

/*存储 单条订单详情 */
const SAVE_ORDERINFO = 'SAVE_ORDERINFO';

/*存储 单条入库单详情 */
const SAVE_WAREHOUINFO = 'SAVE_WAREHOUINFO';

/*存储当前登录的供应商信息 */
const SET_SUPPLIERINFO = 'SET_SUPPLIERINFO'

/*存储送货单列表 */
const SET_DELIVERY = 'SET_DELIVERY'

/*品检单列表 */
const SET_CHECKLIST = 'SET_CHECKLIST'

/*送货单列表 */
const SET_DELIVERY2 = 'SET_DELIVERY2'

/*送货单列表单条信息存储 */
const SET_SINGLEINFO = 'SET_SINGLEINFO'

/*生成送货单 预览 */
const SET_CHOOSEITEM = 'SET_CHOOSEITEM'

/*账单列表 往来对账单列表 */
const SET_BILLLIST = 'SET_BILLLIST'

/*往来对账单接扣列表 参数 */
const SET_BILLPARANS = 'SET_BILLPARANS'

/*品检列表 参数 */
const SAVE_PROCHECKINFO = 'SAVE_PROCHECKINFO'

/*开票须知*/
const SETNOTES = 'SETNOTES'
export default {
  UPDATE_DIRECTION,
  SET_USERINFO,
  GET_USERINFO,
  SAVE_ORDERLIST,
  GET_ORDERLIST,
  SAVE_WAREHOUSINGLIST,
  GET_WAREHOUSINGLIST,
  SAVE_ORDERINFO,
  SAVE_WAREHOUINFO,
  SET_SUPPLIERINFO,
  SET_DELIVERY,
  SET_CHECKLIST,
  SET_DELIVERY2,
  SET_SINGLEINFO,
  SET_CHOOSEITEM,
  SET_BILLLIST,
  SET_BILLPARANS,
  SAVE_PROCHECKINFO,
  SETNOTES
}
